project:
    name: ""
    version: ""
workflow:
    statuses: []
    default_status: ""
templates:
    default: ""
    available:
        - improvement
labels: []
milestones: []
git:
    auto_link: false
    auto_close_keywords: []
    default_branch_prefix: ""
    branch_config:
        template: ""
        prefix_by_type: {}
        max_title_length: 0
        auto_switch: false
        auto_merge_targets: []
ui:
    colors: false
    interactive: false
    pager: ""
    format: ""
storage:
    max_project_size: 524288000
    max_attachment_size: 10485760
    max_total_attachments: 524288000
    max_attachment_age: 0
    enable_auto_cleanup: false
    warning_threshold: 70
    critical_threshold: 95
    enforce_quotas: true
    cleanup:
        enabled: true
        schedule: 0 2 * * *
        retention_days:
            closed_issues: 30
            closed_issue_attachments: 30
            history: 365
            time_entries: 365
            orphaned_attachments: 7
            empty_directories: true
        size_triggers:
            max_total_size: 0
            max_attachments_size: 0
            max_history_size: 0
            trigger_percentage: 90
        archive_before_delete: false
        archive_path: .issuemap_archive
        dry_run_mode: false
        minimum_keep:
            closed_issues: 10
            history_per_issue: 5
            time_entries_per_issue: 5
